{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service-chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "service-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.port.name }}
      port: {{ .Values.port.number }}
      targetPort: {{ .Values.port.number }}
    {{- if include "service-chart.separateProbePort" . }}
    - name: probe
      port: {{ .Values.probePort }}
      targetPort: {{ .Values.probePort }}
    {{- end }}
{{- end }}
